networks:
  database:

volumes:
  mysql:

services:
  proxy:
    image: nginx:1.26-alpine3.19
    depends_on:
      - db
      - phpmyadmin
    networks:
      - database
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf.d:/etc/nginx/conf.d:ro
      - ./backend:/www:rw

  db:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - TZ=${TZ}
    volumes:
      - "mysql:/var/lib/mysql:rw"
    ## ports:
    ##  - 3306:3306
    networks:
      - database
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$DB_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: rcsnjszg/phpmyadmin:5.2.1-apache
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - UPLOAD_LIMIT=300M
    networks:
      - database
